name: "Composite action"
description: "Action used to access specific websites"

inputs:
  website_url:
    description: 'The website url to be accessed'
    required: true
  dummy_token:
    description: dummy secret
    required: true

runs:
  using: "composite"
  steps:
   - name: Access the website
     run: |
       curl ${{ inputs.website_url }}
       echo "the dummy token is ${{ inputs.dummy_token }}"
     shell: "bash"
